-- =============================================
-- THÊM CÂU HỎI PYTHON (100 câu nữa)
-- =============================================

INSERT INTO python_questions (question, answer, hint, difficulty, category) VALUES
-- LEVEL 1: Cơ bản (thêm 25 câu)
('5 + 3 = ?', '8', 'Phép cộng', 1, 'Math'),
('10 - 4 = ?', '6', 'Phép trừ', 1, 'Math'),
('3 * 4 = ?', '12', 'Phép nhân', 1, 'Math'),
('15 / 3 = ?', '5.0', 'Phép chia', 1, 'Math'),
('type([]) = ?', 'list', 'Danh sách rỗng', 1, 'Types'),
('type({}) = ?', 'dict', 'Dictionary rỗng', 1, 'Types'),
('type(()) = ?', 'tuple', 'Tuple rỗng', 1, 'Types'),
('type(True) = ?', 'bool', 'Boolean type', 1, 'Types'),
('len('''') = ?', '0', 'String rỗng', 1, 'String'),
('len([]) = ?', '0', 'List rỗng', 1, 'List'),
('''a'' + ''b'' = ?', 'ab', 'Nối string', 1, 'String'),
('[1] + [2] = ?', '[1, 2]', 'Nối list', 1, 'List'),
('not True = ?', 'false', 'Phủ định', 1, 'Logic'),
('not False = ?', 'true', 'Phủ định', 1, 'Logic'),
('True and False = ?', 'false', 'Phép AND', 1, 'Logic'),
('True or False = ?', 'true', 'Phép OR', 1, 'Logic'),
('1 == 1 = ?', 'true', 'So sánh bằng', 1, 'Logic'),
('1 != 2 = ?', 'true', 'So sánh khác', 1, 'Logic'),
('5 > 3 = ?', 'true', 'So sánh lớn hơn', 1, 'Logic'),
('2 < 1 = ?', 'false', 'So sánh nhỏ hơn', 1, 'Logic'),
('3 >= 3 = ?', 'true', 'Lớn hơn hoặc bằng', 1, 'Logic'),
('4 <= 5 = ?', 'true', 'Nhỏ hơn hoặc bằng', 1, 'Logic'),
('''hello''[0] = ?', 'h', 'Ký tự đầu', 1, 'String'),
('[1,2,3][-1] = ?', '3', 'Phần tử cuối', 1, 'List'),
('bool(1) = ?', 'true', '1 là truthy', 1, 'Types'),

-- LEVEL 2: Trung bình (thêm 25 câu)
('list(range(3)) = ?', '[0, 1, 2]', 'range tạo list', 2, 'List'),
('list(range(1,4)) = ?', '[1, 2, 3]', 'range với start', 2, 'List'),
('list(range(0,10,2)) = ?', '[0, 2, 4, 6, 8]', 'range với step', 2, 'List'),
('''hello''.capitalize() = ?', 'Hello', 'Viết hoa chữ đầu', 2, 'String'),
('''hello world''.title() = ?', 'Hello World', 'Viết hoa mỗi từ', 2, 'String'),
('''  hello  ''.strip() = ?', 'hello', 'Xóa khoảng trắng', 2, 'String'),
('''hello''.find(''l'') = ?', '2', 'Tìm vị trí ký tự', 2, 'String'),
('''hello''.index(''e'') = ?', '1', 'Index của ký tự', 2, 'String'),
('[1,2,3].index(2) = ?', '1', 'Index trong list', 2, 'List'),
('[1,2,2,3].count(2) = ?', '2', 'Đếm phần tử', 2, 'List'),
('sorted([3,1,2], reverse=True) = ?', '[3, 2, 1]', 'Sắp xếp giảm', 2, 'List'),
('[1,2,3].pop() = ?', '3', 'Lấy phần tử cuối', 2, 'List'),
('len({1,2,3}) = ?', '3', 'Độ dài set', 2, 'Types'),
('{1,2} & {2,3} = ?', '{2}', 'Giao của set', 2, 'Types'),
('{1,2} - {2,3} = ?', '{1}', 'Hiệu của set', 2, 'Types'),
('2 in [1,2,3] = ?', 'true', 'Kiểm tra tồn tại', 2, 'List'),
('4 in [1,2,3] = ?', 'false', 'Không tồn tại', 2, 'List'),
('''a'' in ''abc'' = ?', 'true', 'Ký tự trong string', 2, 'String'),
('round(3.14159, 2) = ?', '3.14', 'Làm tròn 2 số', 2, 'Math'),
('abs(-10) = ?', '10', 'Giá trị tuyệt đối', 2, 'Math'),
('pow(2, 4) = ?', '16', '2 mũ 4', 2, 'Math'),
('''abc''.isalpha() = ?', 'true', 'Chỉ có chữ cái', 2, 'String'),
('''123''.isdigit() = ?', 'true', 'Chỉ có số', 2, 'String'),
('''abc123''.isalnum() = ?', 'true', 'Chữ và số', 2, 'String'),

-- LEVEL 3: Khó (thêm 25 câu)
('[1,2,3][::2] = ?', '[1, 3]', 'Slice với step', 3, 'List'),
('[1,2,3,4,5][1::2] = ?', '[2, 4]', 'Slice phức tạp', 3, 'List'),
('''python''[::2] = ?', 'pto', 'String slice', 3, 'String'),
('dict.fromkeys([''a'',''b''], 0) = ?', '{''a'': 0, ''b'': 0}', 'Tạo dict từ keys', 3, 'Dict'),
('{''a'':1}.get(''b'', 0) = ?', '0', 'Get với default', 3, 'Dict'),
('{''a'':1, ''b'':2}.keys() = ?', 'dict_keys([''a'', ''b''])', 'Lấy keys', 3, 'Dict'),
('{''a'':1, ''b'':2}.values() = ?', 'dict_values([1, 2])', 'Lấy values', 3, 'Dict'),
('list({''a'':1}.items()) = ?', '[(''a'', 1)]', 'Dict items', 3, 'Dict'),
('oct(8) = ?', '0o10', 'Bát phân', 3, 'Math'),
('int(''1010'', 2) = ?', '10', 'Nhị phân sang thập phân', 3, 'Math'),
('int(''ff'', 16) = ?', '255', 'Hex sang thập phân', 3, 'Math'),
('''hello''.zfill(10) = ?', '00000hello', 'Thêm số 0', 3, 'String'),
('''hello''.center(11) = ?', '   hello   ', 'Căn giữa', 3, 'String'),
('''hello''.ljust(10) = ?', 'hello     ', 'Căn trái', 3, 'String'),
('''hello''.rjust(10) = ?', '     hello', 'Căn phải', 3, 'String'),
('bool([]) = ?', 'false', 'List rỗng falsy', 3, 'Types'),
('bool({}) = ?', 'false', 'Dict rỗng falsy', 3, 'Types'),
('bool(None) = ?', 'false', 'None là falsy', 3, 'Types'),
('[1,2,3][::-1] = ?', '[3, 2, 1]', 'Đảo ngược list', 3, 'List'),
('list(zip([1,2],[3,4])) = ?', '[(1, 3), (2, 4)]', 'Zip 2 list', 3, 'List'),
('list(enumerate([''a'',''b''])) = ?', '[(0, ''a''), (1, ''b'')]', 'Enumerate', 3, 'List'),
('sum([1,2,3], 10) = ?', '16', 'Sum với start', 3, 'Math'),
('max(''hello'') = ?', 'o', 'Max trong string', 3, 'String'),
('min(''hello'') = ?', 'e', 'Min trong string', 3, 'String'),
(''',''.join([''a'',''b'',''c'']) = ?', 'a,b,c', 'Join với dấu phẩy', 3, 'String'),

-- LEVEL 4: Chuyên gia (thêm 25 câu)
('list(filter(None, [0,1,2,'''',3])) = ?', '[1, 2, 3]', 'Filter truthy', 4, 'Lambda'),
('list(map(str, [1,2,3])) = ?', '[''1'', ''2'', ''3'']', 'Map to string', 4, 'Lambda'),
('[x for x in range(10) if x%2==0] = ?', '[0, 2, 4, 6, 8]', 'List comp với if', 4, 'List'),
('{x:x**2 for x in range(4)} = ?', '{0: 0, 1: 1, 2: 4, 3: 9}', 'Dict comprehension', 4, 'Dict'),
('{x for x in [1,1,2,2,3]} = ?', '{1, 2, 3}', 'Set comprehension', 4, 'Types'),
('(x**2 for x in range(3)) type = ?', 'generator', 'Generator expression', 4, 'Types'),
('sorted([''b'',''a'',''c''], key=str.upper) = ?', '[''a'', ''b'', ''c'']', 'Sort với key', 4, 'List'),
('max([1,2,3], key=lambda x:-x) = ?', '1', 'Max với key', 4, 'Lambda'),
('min([1,2,3], key=lambda x:-x) = ?', '3', 'Min với key', 4, 'Lambda'),
('all([]) = ?', 'true', 'All của list rỗng', 4, 'Logic'),
('any([]) = ?', 'false', 'Any của list rỗng', 4, 'Logic'),
('hasattr([], ''append'') = ?', 'true', 'Kiểm tra attribute', 4, 'Types'),
('callable(len) = ?', 'true', 'Kiểm tra callable', 4, 'Types'),
('type(lambda x:x) = ?', 'function', 'Type của lambda', 4, 'Types'),
('(lambda x,y:x+y)(2,3) = ?', '5', 'Lambda với 2 tham số', 4, 'Lambda'),
('list(reversed(range(3))) = ?', '[2, 1, 0]', 'Reversed range', 4, 'List'),
('sorted(''cba'') = ?', '[''a'', ''b'', ''c'']', 'Sort string', 4, 'String'),
('''{0} {1}''.format(''a'',''b'') = ?', 'a b', 'String format', 4, 'String'),
('f''{2+3}'' = ?', '5', 'F-string expression', 4, 'String'),
('__name__ trong module chính = ?', '__main__', 'Module name', 4, 'Types'),
('[*[1,2], *[3,4]] = ?', '[1, 2, 3, 4]', 'Unpacking list', 4, 'List'),
('{**{''a'':1}, **{''b'':2}} = ?', '{''a'': 1, ''b'': 2}', 'Unpacking dict', 4, 'Dict'),
('divmod(17, 5) = ?', '(3, 2)', 'Chia và dư', 4, 'Math'),
('complex(3, 4).real = ?', '3.0', 'Phần thực', 4, 'Math'),
('complex(3, 4).imag = ?', '4.0', 'Phần ảo', 4, 'Math')
ON CONFLICT DO NOTHING;
